name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run application
      env:
        FLASK_APP: app.py
        FLASK_ENV: production
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TRANSLATION_API_ENDPOINT: ${{ secrets.TRANSLATION_API_ENDPOINT }}
      run: |
        gunicorn -w 4 -b 0.0.0.0:5000 app:app
